### POST Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "peach@mail.com",
  "password": "password"
}
> {% client.global.set("auth_token", response.body.data.token); %}

### GET request to example server
GET http://localhost:8080/api/merchant/ab532205-dcc5-41ac-98c9-f9ee2b039aac
Authorization: Bearer {{auth_token}}
Content-Type: application/json
###

GET http://localhost:8080/api/merchant/ab532205-dcc5-41ac-98c9-f9ee2b039aac/payments
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

POST http://localhost:8080/api/payment
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "amount": 1,
  "merchant_id": "ab532205-dcc5-41ac-98c9-f9ee2b039aac",
  "customer_id": "10634aaf-9372-47f8-9a57-22416d54beb7",
  "payment_method_id": "b80ee8d7-c9d2-4815-867e-4a17507bf81e"
}

###

GET http://localhost:8080/api/payment/f65ec669-c0dd-4094-b787-b8869f0eedbb
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

POST http://localhost:8080/api/payment/f65ec669-c0dd-4094-b787-b8869f0eedbb/process
Authorization: Bearer {{auth_token}}
Content-Type: application/json

###

POST http://localhost:8080/api/payment/f65ec669-c0dd-4094-b787-b8869f0eedbb/refund
Authorization: Bearer {{auth_token}}
Content-Type: application/json


