### GET request to example server
GET http://localhost:8080/api/merchant/ab532205-dcc5-41ac-98c9-f9ee2b039aac

###

GET http://localhost:8080/api/merchant/ab532205-dcc5-41ac-98c9-f9ee2b039aac/payments
Content-Type: application/json

###

POST http://localhost:8080/api/payment
Content-Type: application/json

{
  "amount": 1,
  "merchant_id": "ab532205-dcc5-41ac-98c9-f9ee2b039aac",
  "customer_id": "10634aaf-9372-47f8-9a57-22416d54beb7",
  "payment_method_id": "b80ee8d7-c9d2-4815-867e-4a17507bf81e"
}

###

GET http://localhost:8080/api/payment/5343dec9-6f75-407b-9291-b1a5e52a9085
Content-Type: application/json

###

POST http://localhost:8080/api/payment/5343dec9-6f75-407b-9291-b1a5e52a9085/process
Content-Type: application/json

###

POST http://localhost:8080/api/payment/5343dec9-6f75-407b-9291-b1a5e52a9085/refund
Content-Type: application/json


